import { Cairo } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import "./globals.css";
import Footer from "./Footer.jsx";

const cairo = Cairo({
  subsets: ["latin", "arabic"],
  variable: "--font-cairo",
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "t-shirt editor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="">
      <body className={cairo.className}>
    <body import Script from "next/script";>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2393776775889919"
     crossorigin="anonymous"></script>
        {children}
        <Footer />
      </body>
    </html>
  );
}
